version: "3"
services:

  pgsql:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - testgin

  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    environment:
      - DATABASE_USER=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - DATABASE_NAME=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
    ports:
      - '8000:8000'
    volumes:
      - .:/opt/app/api
    depends_on:
      - pgsql
    links:
      - pgsql
    networks:
      - testgin

networks:
  testgin:
    driver: bridge

volumes:
  pgdata:
